name: Setup
description: Sets up the job
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      shell: bash
      run: bun install
