name: Integrate

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Set up
  #       uses: ./.github/actions/setup
  #     - name: Run Vitest
  #       run: pnpm test
